### PR TITLE
Use gem directory in home for "bundle install"

### PR DESCRIPTION
**Pull request by njam**
For when the global gem directory is not writable by current user.

cc @tomaszdurka @kris-lab

### CODE REVIEW

**Comment by njam** [comment]
The reasoning is that we want to run `pulsar` as a user without root-privileges. This user cannot install system-wide ruby gems, so the `bundle install` fails.
Using a gem directory within the user's home seems reasonable. Bundler's suggestion is `~/.bundle/`.

@mtylty wdyt?

**Comment by mtylty** [comment]
@njam I'm not sure this is particularly needed.

From what I see on the [bundler docs](http://bundler.io/v0.9/bundle_install.html) you guys should be able to achieve what you need simply by setting the `BUNDLE_PATH` environment variable (which defaults to `~/.bundle`).

Have you tried setting `BUNDLE_PATH` first?

**Comment by njam** [comment]
Agree, one can work around this (by using `BUNDLE_PATH`). But it needs to be done explicitly. It seems recent `bundler` versions don't have a default for `$BUNDLE_PATH` anymore (the docu you linked to is 0.7).
[1.7 docu](http://bundler.io/v1.7/bundle_install.html) says:
> `--path`: Specify a different path than the system default ($BUNDLE_PATH or $GEM_HOME). Bundler will remember this value for future installs on this machine

So by default neither of these environment variables will be set and the system's default "gem path" will be used (on Debian `/var/lib/gems/1.9.1`), which is usually not world-writable.

My reasoning is that somebody should be able to run `pulsar` without even knowing that it uses `bundler` internally and that it will install dependencies. If that somebody is not `root` (and can't `sudo`) he needs to use a bundler-directory which he can write to. wdyt?

**Comment by mtylty** [comment]
I see your point but I'm not so sure this needs to be pulsar's responsibility... I've never met someone who doesn't use rbenv or rvm or some other ruby version manager... and that should solve the problem altogether...

I mean if you're trying to install something you should be able to install and the system won't let you because it expects you to run that tool as root it should probably be the system's resposibilty...

Putting pulsar aside for a moment... If you think about it you would have the same problem when running a simple `gem install pulsar` from the command line running as the non-root user, right? So I'd say it's Debian that needs to be configured, not the ruby environment itself...

What do you think about it?

**Comment by njam** [comment]
I might be bit *old-fashioned*, but I think there's a difference between installing software system-wide (which includes installing binaries on the $PATH), and installing  project dependencies in a *local* directory.

I install *pulsar* with `gem` on my system with root privileges. I expect it to run for all users on the system. When I actually run it as a user it uses `gem` (or `bundler`) to install dependencies for the current task. This could happen all in the scope of my user, and I think it should.

If each user on the system could install gem dependencies in a global location then wouldn't that be a security problem, as one user might change the gems used by another user?
This could be solved by using rvm or rbenv I agree. But that also adds more complexity to the whole setup.

Using a specific `--path` (which is still widely used) still seems like a good approach for making sure *pulsar* is portable and runs in many environments. I'm not sure whether it has any downsides?

Please feel free to close this ticket, and I'll shut up ;) (there are workarounds)

**Comment by mtylty** [comment]
To be honest... I'm not closing this ticket because I can't see any downsides :smile: but at the same time I feel like it will make pulsar harder to use in some cases... For example, what happens if `Dir.home` is not defined?

**Comment by njam** [comment]
Agree, it can be problematic when you run it as system user which doesn't have a home directory. Since that's an uncommon case I think we could allow to configure a different "home"?

I've pushed a new suggestion, it's highly [influenced by vagrant](https://github.com/mitchellh/vagrant/blob/v1.7.2/lib/vagrant/shared_helpers.rb#L82).
wdyt?

**Comment by njam** [comment]
Thanks! :love_letter:

**Comment by mtylty** [comment]
Thanks for taking the time to add this awesome feature! :+1:

**Pull request merged**
